### ISSUE TITLE
[add] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by KWY0218** [HapdongSeminarApp4/Android_Korail#1]
## ISSUE
- 프로젝트 초기 세팅

## To-Do
- [x] hilt application 생성
- [x] text appearance 추가
- [x] color 추가
- [x] 인터넷 퍼미션
- [x] status bar color 설정
